### ISSUE TITLE
Insufficient Testing

### ISSUE THREAD

**Issue by jennmcguire** [phys201/icetemp#14]
Your current unit testing covers only approximately 53% of model.py and 83% of data_io.py. In data_io you seem to be missing tests for timeify specifically, and in model you are missing tests for fit_quad_MCMC. Be sure to check that you are thoroughly testing your code.

**Comment by amulski** [comment]
`timeify()` in `data_io.py` removed, as it was no longer needed

**Comment by amulski** [comment]
Now testing all functions in `data_io.py` and `model.py`
