### ISSUE TITLE
tutorial takes a long time to run

### ISSUE THREAD

**Issue by barkls** [phys201/icetemp#16]
The tutorial notebook takes a long time to run. Remember that it's meant to introduce the capabilities of your package, not do any actual analysis. For example, you probably don't need to run MCMC sampling on each of the different years with different orders of polynomials. One example is enough.

**Comment by diyaselis** [comment]
We have moved the majority of the inference testing to a new notebook called **_analysis.ipynb_**. In this new notebook we use all datesets for the multiple years. Thus, in the tutorial notebook only one dataset is considered; however we make sure to showcase all our model functions.

**Comment by amulski** [comment]
Additional functionality was added to multiple methods to make running tutorial notebook more streamlined. Closing issue.
