### ISSUE TITLE
Gaussian process regression missing amplitude term

### ISSUE THREAD

**Issue by barkls** [phys201/icetemp#17]
When using GPR, you generally want to infer 2 parameters in the covariance matrix - the length scale and amplitude. The length scale determines how quickly the correlation drops off for points that are farther away, and the amplitude determines how correlated nearby points are and how much all data points deviate from the mean. You can introduce an amplitude parameter and multiply it by your squared exponential covariance matrix to achieve this.

**Comment by amulski** [comment]
Amplitude term now included
