### ISSUE TITLE
tutorial notebook doesn't explain where priors come from

### ISSUE THREAD

**Issue by vnmanoharan** [phys201/icetemp#2]
I'm not sure where you're getting your bounds on your uniform priors.  It seems like you might be trying to get these from the data -- if so, re-think the priors.  The prior values should be chosen independently of any particular data set.

**Comment by diyaselis** [comment]
We have implemented some changes and indeed introducing som ranges in the priors without looking at the data. They were more based on the information on the temperature in Antartica and the assumption of a slow steady (increasing) global warming. We will take a more indepth look at the prior ranges and if it's worth considering a Jeffreys prior.
