### ISSUE TITLE
tutorial notebook should do some inference

### ISSUE THREAD

**Issue by vnmanoharan** [phys201/icetemp#3]
Tutorial notebook should do some inference on the simulated data to check that it returns the parameters you are expecting.

**Comment by vnmanoharan** [comment]
Main problem here is that model.py doesn't have any functions for fitting.

**Comment by amulski** [comment]
Comments addressed with previous two commits. Added simple function to fit data to a quadratic in `model.py`. Notebook now uses that function to infer the parameters used to generate the quadratic test data.
