### ISSUE TITLE
tests take too long to run

### ISSUE THREAD

**Issue by barkls** [phys201/icetemp#6]
Your tests take over a minute to run. They should run in a few seconds at most. Make sure you aren't doing any actual inference calculations in your tests.

**Comment by vnmanoharan** [comment]
Or if you want to test inference, make sure to separate out those tests so that they don't run by default.

**Comment by bakerl12** [comment]
Peer feedback: I was able to run 9 tests in 7.167s

**Comment by diyaselis** [comment]
We took care of the inference that was going on inside the tests. Should be working as expected. Thanks Lauren for confirming.
