### ISSUE TITLE
peer feedback - define all variables in tutorial equations

### ISSUE THREAD

**Issue by bakerl12** [phys201/icetemp#7]
Generally clear, coded appropriately, and efficient (ran all 9 tests in 7.167s)

For completeness, in addition to defining T and d, it would be best to define all variables you have in the equations in your tutorial notebook (i.e. sigma_T, m, b, x, y, q, etc).

**Comment by diyaselis** [comment]
Thank you, will take this into consideration. To quickly answer your thoughts sigma_T is implicitly defined. As for the case of q,m,b these are the parameters of the quadratic function (not so much of a definition but a purpose), it will then be helpful to define the y and x as our data point of T and d, respectively.
