### ISSUE TITLE
peer feedback - check trace plots for real data

### ISSUE THREAD

**Issue by bakerl12** [phys201/icetemp#9]
What happened to the trace plot for 2009 and 2010 real data? They look much different than the test inference and real 2007 plot

**Comment by diyaselis** [comment]
Indeed, this is a concern of ours. The noticeable difference is that for the real data 2009 and 2010, we would need to manually increase the number of tuning steps. That may not solve to problem, stay tuned for updates.

**Comment by amulski** [comment]
The model and initial guesses have been updated to fix the divergences and speed up MCMC
